### ISSUE TITLE
Add option to enter the quantity of an item when adding to the shopping cart

### ISSUE THREAD

**Issue by Gladhus** [Gladhus/simple-store#2]
Right not, the only way to add more than one item to the shopping cart is to click "add to shopping cart" multiple times. 

It would be better if there was an option to enter the quantity of the item we want to add to the shopping cart.

**Comment by illegalDisease** [comment]
I got this. Started working on it.

**Comment by illegalDisease** [comment]
Struugled for 3 days to make the application work. Catalog items are not shown. I configured application-dev.properties, tried debugging both maven and angular-cli. At the client side,  there is some error : 

```
ReferenceError: Product is not defined
    at eval (eval at CatalogComponent (http://localhost:4200/main.bundle.js:104:9), <anonymous>:1:1)
    at new CatalogComponent (http://localhost:4200/main.bundle.js:104:9)
    at new Wrapper_CatalogComponent (/AppModule/CatalogComponent/wrapper.ngfactory.js:7:18)
    at CompiledTemplate.proxyViewClass.View_CatalogComponent_Host0.createInternal 
```

This probably caused by the database. Applicaton-dev.properties : 

```
spring.datasource.url=jdbc:mysql://localhost:3306/simplestore?useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
```

I am stuck :(

**Comment by Gladhus** [comment]
Hey! Thanks for your work, I have been told about this issue from another dev on another ticket. I have pushed a correction and it should work now.

**Comment by illegalDisease** [comment]
Thanks, i will pull and try again tonight.
